baseURL = "/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "papermod"
paginate = 5

[params]
  # PaperMod theme parameters
  env = "production"
  description = "My blog powered by Hugo and PaperMod"
  author = "Author"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  comments = false
  
[params.homeInfoParams]
  Title = "Welcome to my blog"
  Content = "This is a Hugo blog created with HugoHost"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
