baseURL = "https://example.com"
languageCode = "en-us"
title = "mmmmv"
theme = "ananke"
googleAnalytics = "UA-XXXXXXXXX-Y"

[params]
  description = "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm"

