name = "PaperMod"
license = "MIT"
licenselink = "https://github.com/adityatelange/hugo-PaperMod/blob/master/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://github.com/adityatelange/hugo-PaperMod"
tags = ["responsive", "simple", "clean", "light", "dark", "blog"]
features = ["responsive", "single-column", "blog", "cover-image", "table-of-contents"]
min_version = "0.83.0"

[author]
  name = "Aditya Telange"
  homepage = "https://github.com/adityatelange"